version: "3"
services:
  immocdb:
    restart: always
    image: mysql:latest
    container_name: immocdb
    environment:
      - "MYSQL_ROOT_PASSWORD=1234567"
    ports:
      - "3306:3306"

  imoocredis:
    restart: always
    image: redis
    container_name: imoocredis
    ports:
      - "6379:6379"